apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              volumeMounts:
                - mountPath: /kcl
                  name: kcl-root
                  readOnly: true
                - mountPath: /kcl/modules/azure
                  name: kcl-modules-azure
                  readOnly: true
                - mountPath: /kcl/modules/k8s
                  name: kcl-modules-k8s
                  readOnly: true
                - mountPath: /kcl/templates
                  name: kcl-templates
                  readOnly: true
                - mountPath: /kcl/templates/azure
                  name: kcl-templates-azure
                  readOnly: true
          volumes:
            - name: kcl-root
              configMap:
                name: kcl-root
            - name: kcl-modules-azure
              configMap:
                name: kcl-modules-azure
            - name: kcl-modules-k8s
              configMap:
                name: kcl-modules-k8s
            - name: kcl-templates
              configMap:
                name: kcl-templates
            - name: kcl-templates-azure
              configMap:
                name: kcl-templates-azure
